### ISSUE TITLE
Non-Broadcasters can change channel prefix

### ISSUE THREAD

**Issue by ghostzero** [shardick/twitch-commando#7]
Currently it is possible to change the prefix for some users. I don't know why, but this already happens twice:

Version: `twitch-commando@^1.0.5:  version "1.0.7"`

![screenshot-www twitch tv-2020 05 25-22_04_41](https://user-images.githubusercontent.com/6547306/82840866-643a0200-9ed4-11ea-952c-f7d823dfe8b0.png)

**Comment by ghostzero** [comment]
Furthermore, can you implement that you can specify only one character as an argument? and maybe no multibyte characters (like Russian characters)?

For example, there are many people who type `!prefix batman` and think they have `batman` as prefix. It happens very often.

**Comment by dowmeister** [comment]
thanks for reporting it.

**Comment by ghostzero** [comment]
Is this project still active? My ticket is now 2 months open. We are talking about a security gap where normal users can act as broadcasters. In addition, 5 pull requests are still open where dependencies have been updated.

It would be a pity if I had to change the software due to inactivity. I use the software for 3 verified bots with tens of thousands of active users.

**Comment by dowmeister** [comment]
Hi,
yes, the project is still active.
But you know, maintainers keep up the work at best effort without any assurance the project will live forever. I was too busy to take care of it.
If you was so concerned about the security issues, you could send a PR :)

Now the issue is fixed, just released npm package 1.0.11 fixing the security issue and permitting prefix with more characters.
